language: swift
osx_image: xcode10.2
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=Authentication.xcworkspace
  - SCHEME="Authentication"

  matrix:
    - DESTINATION="name=iPhone X,OS=12.0" RUN_TEST="YES"
    - DESTINATION="name=iPhone X,OS=11.4" RUN_TEST="YES"
before_install:
  - gem install cocoapods --prerelease --no-document --quiet
  - pod update
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build in Debug
  - if [ $RUN_TEST == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration test | xcpretty;
    else 
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration build | xcpretty;
    fi
